### ISSUE TITLE
caesar_book.cls needs twoopt.sty

### ISSUE THREAD

**Issue by WGNettles** [andythomas/TeX-sidenotes#36]
I was trying to test `caesar_book.cls` for something I'm writing. I got an error for unrecognized command `\newcommandtwoopt`.  When I look at the code I don't see a RequiresPackage for twoopt. Am I missing something?

**Comment by andythomas** [comment]
The package 'mhchem' subsequently loads 'twoopt'. It works for an unchanged caesar_book for me.

**Comment by WGNettles** [comment]
Andy,
The latest update of mhchem: \ProvidesPackage{mhchem}[2015/02/09 v3.19 for typesetting chemical formulae]
It does not load twoopt.


When I run the following code:

\documentclass{caesar_book}
\usepackage{mhchem}
\usepackage{sidenotes}
\usepackage{lipsum}
\begin{document}
\chapter{First}
\lipsum
\chapter{second}
\lipsum
\end{document}

I get a whole set of errors starting with
Undefined control sequence \newcommandtwoopt at line 138 of caesar_book.cls

When I insert \RequirePackage{twoopt} in caesar_book.cls everything works.

Thanks for responding,
Bill
________________________________

**Comment by andythomas** [comment]
The `\sidecite` macro uses it, but this macro is not officially supported any more. I forgot to take it out after milestone 1. I will try several things how to address it without breaking backwards compatibility too much.
