### ISSUE TITLE
sidenotes seems to have stopped working with new xparse

### ISSUE THREAD

**Issue by onstrees** [andythomas/TeX-sidenotes#41]
With 'seems to have stopped working', I mean it definitely does not work any more, but I assume it did so before.

I have to be very carefull what I say here, because I am completely new to (La)Tex; on february 28 I installed TexLive using TexLive's own online installer install-tl-20170223 on Xubuntu 16.04.2 x64. But I am not the first to have bumped into this problem, although apparently nobody cared to report it to you. See e.g. [Weird output from the sidenotes package](http://tex.stackexchange.com/questions/355914/weird-output-from-the-sidenotes-package).

A reply on that url links the problem to a change in the latest version of the xparse package, which I think may be similar to this issue : [xparse's document commands used in math su(p|b)scripts with no brace give error #338](https://github.com/latex3/latex3/issues/338)

This simple code
```LaTex
\documentclass{book}
\usepackage{sidenotes}
\begin{document}
This text is annotated\marginnote{annotation} in the margin.
This text is annotated\footnote{annotation} in the footing.
This text is annotated\sidenote{annotation} in the margin.
\end{document}
```
gives the following error messages, all on the line with the call to `\sidenote` macro:
```Missing number, treated as zero. This text is annotated\sidenote{annotation}
Illegal unit of measure (pt inserted). This text is annotated\sidenote{annotation}
Missing number, treated as zero. This text is annotated\sidenote{annotation}
Illegal unit of measure (pt inserted). This text is annotated\sidenote{annotation}
Missing number, treated as zero. This text is annotated\sidenote{annotation}
Illegal unit of measure (pt inserted). This text is annotated\sidenote{annotation}
Missing number, treated as zero. This text is annotated\sidenote{annotation}
Illegal unit of measure (pt inserted). This text is annotated\sidenote{annotation}
Missing number, treated as zero. This text is annotated\sidenote{annotation}
Illegal unit of measure (pt inserted). This text is annotated\sidenote{annotation}
```
Commenting out that `\sidenote`-line gives a nice result with a note in the margin and another one in the footing.

The reply I mentioned, also suggests a workaround that makes the `\sidenote` macro work again:
```LaTeX
\makeatletter
\renewcommand* \@sidenotes@multisign {3sp}
\makeatother
```
sidenotes package is version 40658 (1.00)
xparse package is in l3packages, which is version 43183 (SVN 6878)

**Comment by andythomas** [comment]
It was an issue, but now it works for me on TeX Live 2019.
